apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-api
  namespace: default
  labels:
    app: devops-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devops-api
  template:
    metadata:
      labels:
        app: devops-api
    spec:
      containers:
        - name: devops-api
          image: med25amine/devops-api:latest
          ports:
            - containerPort: 8080  # Port 8080 (5000 et 3000 déjà utilisés)
          env:
            - name: PORT
              value: "8080"
            - name: ENV
              value: "production"
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "200m"
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
